language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck

services:
 - xvfb

script: 
  # Build and run tests
  - qmake -qt=qt5
  - make --silent
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 

after_success:
  - bash <(curl -s https://codecov.io/bash)

